# Generated by Django 3.2.23 on 2024-02-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newmo3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aaaa', models.BigIntegerField()),
                ('vxx', models.BigIntegerField()),
            ],
        ),
    ]
